<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-13 23:10
=======
# Generated by Django 4.2.6 on 2023-11-13 01:17
>>>>>>> a431bcdd890fc5ab147241befc0c56eacb30ea45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0012_dominio_fechasolicitud_dominio_tiempopropiedad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('archivoId', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
<<<<<<< HEAD
=======
                ('sitioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.sitioweb')),
>>>>>>> a431bcdd890fc5ab147241befc0c56eacb30ea45
            ],
        ),
    ]
